<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeploymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeploymentRepository extends EntityRepository
{
    public function getDeploymentsCount($eruType = null)
    {
        $qb = $this->createQueryBuilder('d')
            ->select('count(d.id)');

        if ($eruType) {
            $qb
                ->join('d.operation','o')
                ->join('o.eruTypes','e', 'WITH', 'e.name = :eruType')
                ->setParameter(':eruType', $eruType);
        }

        return $qb->getQuery()->getSingleScalarResult();
    }
}
