<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends EntityRepository
{
    public function getOperationsCount($eruType = null)
    {
        $qb = $this->createQueryBuilder('o')
            ->select('count(o.id)');

        if ($eruType) {
            $qb
                ->join('o.eruTypes','e', 'WITH', 'e.name = :eruType')
                ->setParameter(':eruType', $eruType);
        }

        return $qb->getQuery()->getSingleScalarResult();
    }
}
